version: "3.8"

services:
  nginx:
    container_name: nginx-server
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - nginx-data:/usr/share/nginx
      - nginx-data:/etc/nginx

  pg:
    container_name: pg-server
    image: postgres:alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'n71B1huJ4LgfxJOOvq'
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin-server
    image: dpage/pgadmin4:latest
    ports:
      - "5050:5050"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: 'rmvSQnPsnLK32Ab7YD'
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
      container_name: redis-server
      image: redis:alpine
      restart: always
      command: ["redis-server", "/data/redis.conf"]
      ports:
       - "6379:6379"
      volumes:
       - redis-data:/data

      environment:
       - REDIS_REPLICATION_MODE=master

volumes:
  nginx-data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /tmp/nginx
  pg-data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /tmp/postgres
  pgadmin-data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /tmp/pgadmin
  redis-data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /tmp/redis
